# Numpy  Functions

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [5]:
# linspace
arr = np.linspace(1, 5, 10)
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [7]:
# zeros
arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
arr = np.eye(4)
print(arr) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# random
arr = np.random.rand(2, 3)
print(arr)

[[0.51664307 0.8413913  0.56414324]
 [0.30842872 0.19626426 0.25284549]]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15


In [21]:
arr = np.array([[1, 2], [3, 4]])
print(np.mean(arr))

2.5


In [23]:
# array range
range_arr = np.arange(1, 10, 2)
range_arr

array([1, 3, 5, 7, 9])

In [24]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# concatenate
concatenated_arr = np.concatenate((arr, arr))
concatenated_arr

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [33]:
transposed_arr = arr.transpose()
transposed_arr

array([[1, 3],
       [2, 4]])

In [39]:
arr_min = np.min(arr)
arr_min

1

In [40]:
# sum
arr_sum  = np.sum(arr)
arr_sum

10

In [41]:
# max
arr_max = np.max(arr)
arr_max

4

In [42]:
dot_product = np.dot(arr, arr)
dot_product

array([[ 7, 10],
       [15, 22]])

In [47]:
# absolute
absolute_values = np.abs(2.99)
absolute_values

2.99

In [45]:
# sqrt
square_root = np.sqrt(2)
square_root

1.4142135623730951

In [49]:
# exponent
exponential_values = np.exp(10)
exponential_values

22026.465794806718

In [50]:
# percentile
per = np.percentile(arr, 50)
per

2.5

In [51]:
cov_matrix = np.cov(arr)
cov_matrix

array([[0.5, 0.5],
       [0.5, 0.5]])

In [53]:
sqrt_result = np.sqrt(arr)
sqrt_result

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [57]:
# division
div = np.divide(25, 5)
div

5.0

In [58]:
# multiplication
mul = np.multiply(25, 5)
mul

125

In [62]:
# subtraction
sub = np.subtract(-24, -5)
sub

-19